import { createContext, useContext, useState, ReactNode } from 'react';

type Language = 'vi' | 'en';

interface LanguageContextType {
  language: Language;
  setLanguage: (lang: Language) => void;
  t: (key: string) => string;
}

const translations = {
  vi: {
    startJourney: 'Bắt đầu hành trình',
    settings: 'Cài đặt',
    language: 'Ngôn ngữ',
    theme: 'Chế độ',
    light: 'Sáng',
    dark: 'Tối',
    vietnamese: 'Tiếng Việt',
    english: 'English',
    searchPlaceholder: 'Hãy nhập địa điểm bạn muốn tìm ở đây (nếu bạn muốn)',
    concept: 'Concept',
    purpose: 'Mục đích',
    amenities: 'Tiện ích',
    budgetRange: 'Khoảng ngân sách',
    numberOfPlaces: 'Số lượng quán',
    search: 'FoOdyssey',
    healthyFood: 'Healthy food',
    specialty: 'Specialty',
    fastFood: 'Fast food',
    vegetarian: 'Vegetarian',
    datingNight: 'Dating night',
    familyGathering: 'Family gathering',
    businessMeeting: 'Business meeting',
    casualHangout: 'Casual hangout',
    soloDining: 'Solo dining',
    carParking: 'Car Parking',
    petFriendly: 'Pet-friendly',
    airConditioned: 'Air-conditioned',
    digitalPayment: 'Digital Payment',
    kidsCorner: "Kid's Corner",
    iWillEatHere: 'I will eat here!',
    holdOn: 'Hold on',
    journeyComplete: 'Hành trình hoàn tất!',
    backToHome: 'Bạn có muốn quay về màn hình chính không?',
    continueBrowsing: 'Tôi muốn xem tiếp',
    yes: 'Có',
    backHome: 'Trở về nhà',
    appTitle: 'FoOdyssey',
    appSubtitle: 'Khám phá hành trình ẩm thực của bạn',
    aiChatPlaceholder: 'Hỏi AI về nhà hàng bạn muốn tìm...',
    aiChatSend: 'Gửi',
    aiChatLoading: 'AI đang suy nghĩ...',
    aiChatError: 'Có lỗi xảy ra. Vui lòng thử lại.',
    aiRecommendationsTitle: 'Gợi ý từ AI',
    aiNoRecommendations: 'Không có gợi ý nào. Hãy thử hỏi khác nhé!',
    radius: 'Bán kính tìm kiếm',
    km: 'km',
    restaurants: 'quán',
    loadingFilters: 'Đang tải bộ lọc...',
    filterError: 'Không tải được bộ lọc từ server',
    useMockData: 'Dùng dữ liệu mẫu',
    searching: 'Đang tìm...',
    noResults: 'Chưa có kết quả',
    noResultsDesc: 'Hãy điều chỉnh bộ lọc và tìm kiếm để xem nhà hàng trên bản đồ',
    openFilters: 'Mở bộ lọc',
    locationDenied: 'Đang sử dụng vị trí mặc định (TP.HCM)',
    mockModeOn: 'Đang dùng dữ liệu mẫu',
    mockModeOff: 'Đang dùng dữ liệu thật',
    refreshMap: 'Làm mới bản đồ',
    switchMockPrompt: 'Đã chuyển chế độ. Vui lòng tìm kiếm lại để cập nhật dữ liệu.',
    price: 'Giá',
    address: 'Địa chỉ',
    phone: 'Điện thoại',
    openingHours: 'Giờ mở cửa',
    description: 'Mô tả',
    loading: 'Đang tải...',

    login: 'Đăng nhập',
    register: 'Đăng ký',
    signIn: 'Đăng nhập',
    welcomeBack: 'Chào mừng bạn trở lại',
    password: 'Mật khẩu',
    savedPlaces: 'Quán đã lưu',
    accountSettings: 'Cài đặt tài khoản',
    logout: 'Đăng xuất',
    smartFeatures: 'Tính năng thông minh',
    scanMenu: 'Quét Menu',
    askAI: 'Hỏi AI',
    addToFavorites: 'Thêm vào yêu thích',
    removeFromFavorites: 'Bỏ yêu thích',
    rememberMe: 'Ghi nhớ đăng nhập',
    createAccount: 'Tạo tài khoản',
    joinUs: 'Tham gia cùng chúng tôi',
    confirmPassword: 'Nhập lại mật khẩu',
    passwordMismatch: 'Mật khẩu không khớp!',
    explore: 'Khám phá',
    exploreArticleTitle: 'Khám phá ẩm thực TP.HCM',
    exploreArticleDesc:
      'Những câu chuyện thú vị về văn hóa ẩm thực Sài Gòn, từ món ăn đường phố đến nhà hàng cao cấp.',
    readMore: 'Đọc thêm',
    topRestaurants: 'Top quán ăn ở TP.HCM',
    restaurant: 'Quán ăn',
    customerReviews: 'Đánh giá khách hàng',
    reviewText:
      'Trải nghiệm tuyệt vời! Đồ ăn ngon, không gian đẹp, phục vụ chu đáo. Chắc chắn sẽ quay lại.',
    reviewer: 'Nguyễn Văn',
    foodLover: 'Người yêu ẩm thực',
    contact: 'Liên hệ',
    legal: 'Pháp lý',
    privacyPolicy: 'Chính sách bảo mật',
    termsOfService: 'Điều khoản sử dụng',
    businessLicense: 'Giấy phép kinh doanh',
    allRightsReserved: 'Đã đăng ký bản quyền',
    footerDescription:
      'Nền tảng khám phá ẩm thực hàng đầu Việt Nam, giúp bạn tìm kiếm và trải nghiệm những hành trình ẩm thực tuyệt vời nhất.',
    exploreHeroTitle: 'Khám phá Ẩm thực TP.HCM',
    exploreHeroDesc:
      'Hành trình khám phá văn hóa ẩm thực Sài Gòn đa dạng và phong phú, từ món ăn đường phố đến nhà hàng cao cấp.',
    categoryStreetFood: 'Ẩm thực đường phố',
    categoryFineDining: 'Nhà hàng cao cấp',
    categoryHealthy: 'Ăn uống lành mạnh',
    categoryNightlife: 'Ẩm thực đêm',
    categoryTraditional: 'Truyền thống',
    categoryFusion: 'Fusion',
    exploreArticle1Title: 'Phở Sài Gòn - Hồn Việt trên từng sợi',
    exploreArticle1Desc:
      'Khám phá câu chuyện đằng sau tô phở truyền thống Sài Gòn và những quán phở nổi tiếng nhất thành phố.',
    exploreArticle2Title: 'Fine Dining - Trải nghiệm đẳng cấp',
    exploreArticle2Desc:
      'Những nhà hàng cao cấp mang đến trải nghiệm ẩm thực đẳng cấp quốc tế ngay tại trung tâm Sài Gòn.',
    exploreArticle3Title: 'Ăn Healthy - Sống Khỏe',
    exploreArticle3Desc:
      'Xu hướng ăn uống lành mạnh và những quán ăn organic, vegan được yêu thích nhất.',
    exploreArticle4Title: 'Ẩm thực Đêm - Sài Gòn không ngủ',
    exploreArticle4Desc:
      'Khám phá những món ăn đêm hấp dẫn và các quán ăn đêm sôi động nhất Sài Gòn.',
    exploreArticle5Title: 'Món Truyền Thống - Hương vị xưa',
    exploreArticle5Desc:
      'Những món ăn truyền thống giữ nguyên hương vị xưa cũ qua nhiều thế hệ.',
    exploreArticle6Title: 'Fusion Food - Sáng tạo không giới hạn',
    exploreArticle6Desc: 'Sự kết hợp độc đáo giữa ẩm thực Việt và các nền ẩm thực thế giới.',
    places: 'quán',
    aiOdysseus: 'Odysseus AI',
    aiAssistant: 'Trợ lý AI',
    restaurantSuggestion: 'Gợi ý quán ăn',
    menuFoodCNN: 'Phân tích hình ảnh',
    aiSelectMode: 'Chọn chế độ',
    aiTypePlaceholder: 'Nhập tin nhắn...',
    aiSend: 'Gửi',
    aiUploadImage: 'Tải ảnh lên',
    aiAnalyzing: 'Đang phân tích...',
    aiViewOnMap: 'Xem trên bản đồ',
    aiDetails: 'Chi tiết',
    aiTranslateMenu: 'Dịch menu',
    aiSuggestingRestaurants: 'Đang tìm quán...',
    aiNoResult: 'Không tìm được kết quả phù hợp.',
    aiWelcomeRestaurant:
      'Xin chào! Tôi là Odysseus. Hãy mô tả món ăn hoặc loại quán bạn muốn, tôi sẽ gợi ý cho bạn!',
    aiWelcomeImage:
      'Xin chào! Hãy tải lên hình ảnh menu, món ăn hoặc địa điểm để tôi phân tích giúp bạn.',
    aiWelcomeAssistant:
      'Xin chào! Tôi là Odysseus, trợ lý AI của FoOdyssey. Tính năng này đang được phát triển.',
    aiComingSoon: 'Tính năng đang phát triển',
    aiImageMenu: 'Đây là menu. Tôi sẽ dịch cho bạn:',
    aiImageFood: 'Đây là món ăn! Các quán có món này:',
    aiImagePlace: 'Đây là một địa điểm! Các địa điểm phù hợp:',
    setYourLocation: 'Tự đặt vị trí của bạn',
    dragToSetLocation: 'Kéo để chọn vị trí',
    confirmLocation: 'Xác nhận vị trí',
    cancel: 'Hủy',
    latestFoodNews: 'Tin tức ẩm thực mới nhất',
    popularArticles: 'Bài viết phổ biến',
    views: 'lượt xem',
    comments: 'bình luận',
    currentLocation: 'Vị trí hiện tại',
    yourLocation: 'Vị trí của bạn',
    loadingMap: 'Đang tải bản đồ...',
    searchError: 'Có lỗi xảy ra khi tìm kiếm',
    loadRestaurantError: 'Không thể tải thông tin nhà hàng',
    filterLoading: 'Đang tải...',
  },
  en: {
    startJourney: 'Start Your Journey',
    settings: 'Settings',
    language: 'Language',
    theme: 'Theme',
    light: 'Light',
    dark: 'Dark',
    vietnamese: 'Tiếng Việt',
    english: 'English',
    searchPlaceholder: 'Enter the location you want to find (optional)',
    concept: 'Concept',
    purpose: 'Purpose',
    amenities: 'Amenities',
    search: 'FoOdyssey',
    healthyFood: 'Healthy food',
    specialty: 'Specialty',
    fastFood: 'Fast food',
    vegetarian: 'Vegetarian',
    datingNight: 'Dating night',
    familyGathering: 'Family gathering',
    businessMeeting: 'Business meeting',
    casualHangout: 'Casual hangout',
    soloDining: 'Solo dining',
    carParking: 'Car Parking',
    petFriendly: 'Pet-friendly',
    airConditioned: 'Air-conditioned',
    digitalPayment: 'Digital Payment',
    kidsCorner: "Kid's Corner",
    iWillEatHere: 'I will eat here!',
    holdOn: 'Hold on',
    journeyComplete: 'Journey Complete!',
    backToHome: 'Would you like to return to the home screen?',
    continueBrowsing: 'Continue browsing',
    yes: 'Yes',
    backHome: 'Back Home',
    appTitle: 'FoOdyssey',
    appSubtitle: 'Discover your culinary journey',
    aiChatPlaceholder: 'Ask AI about restaurants you want to find...',
    aiChatSend: 'Send',
    aiChatLoading: 'AI is thinking...',
    aiChatError: 'An error occurred. Please try again.',
    aiRecommendationsTitle: 'AI Recommendations',
    aiNoRecommendations: 'No recommendations found. Try asking something different!',
    budgetRange: 'Budget Range',
    radius: 'Search Radius',
    numberOfPlaces: 'Number of Results',
    km: 'km',
    restaurants: 'places',
    loadingFilters: 'Loading filters...',
    filterError: 'Could not load filters from server',
    useMockData: 'Use sample data',
    searching: 'Searching...',
    noResults: 'No results yet',
    noResultsDesc: 'Adjust filters and search to see restaurants on the map',
    openFilters: 'Open Filters',
    locationDenied: 'Using default location (Ho Chi Minh City)',
    mockModeOn: 'Using sample data',
    mockModeOff: 'Using real data',
    refreshMap: 'Refresh Map',
    switchMockPrompt: 'Mode switched. Please search again to update data.',
    price: 'Price',
    address: 'Address',
    phone: 'Phone',
    openingHours: 'Opening Hours',
    description: 'Description',
    loading: 'Loading...',

    login: 'Login',
    register: 'Register',
    signIn: 'Sign In',
    welcomeBack: 'Welcome back',
    password: 'Password',
    savedPlaces: 'Saved Places',
    accountSettings: 'Account Settings',
    logout: 'Logout',
    smartFeatures: 'Smart Features',
    scanMenu: 'Scan Menu',
    askAI: 'Ask AI',
    addToFavorites: 'Add to Favorites',
    removeFromFavorites: 'Remove from Favorites',
    rememberMe: 'Remember me',
    createAccount: 'Create Account',
    joinUs: 'Join us today',
    confirmPassword: 'Confirm Password',
    passwordMismatch: 'Passwords do not match!',
    explore: 'Explore',
    exploreArticleTitle: 'Explore HCMC Cuisine',
    exploreArticleDesc:
      'Fascinating stories about Saigon food culture, from street food to fine dining restaurants.',
    readMore: 'Read more',
    topRestaurants: 'Top Restaurants in HCMC',
    restaurant: 'Restaurant',
    customerReviews: 'Customer Reviews',
    reviewText:
      'Amazing experience! Delicious food, beautiful ambiance, excellent service. Will definitely come back.',
    reviewer: 'John Doe',
    foodLover: 'Food Lover',
    contact: 'Contact',
    legal: 'Legal',
    privacyPolicy: 'Privacy Policy',
    termsOfService: 'Terms of Service',
    businessLicense: 'Business License',
    allRightsReserved: 'All rights reserved',
    footerDescription:
      "Vietnam's leading food discovery platform, helping you find and experience the best culinary journeys.",
    exploreHeroTitle: 'Explore HCMC Cuisine',
    exploreHeroDesc:
      'Discover the diverse and rich food culture of Saigon, from street food to fine dining restaurants.',
    categoryStreetFood: 'Street Food',
    categoryFineDining: 'Fine Dining',
    categoryHealthy: 'Healthy Eating',
    categoryNightlife: 'Night Cuisine',
    categoryTraditional: 'Traditional',
    categoryFusion: 'Fusion',
    exploreArticle1Title: 'Saigon Pho - Vietnamese Soul in Every Strand',
    exploreArticle1Desc:
      'Discover the story behind traditional Saigon pho and the most famous pho restaurants in the city.',
    exploreArticle2Title: 'Fine Dining - Premium Experience',
    exploreArticle2Desc:
      'Upscale restaurants offering world-class dining experiences right in the heart of Saigon.',
    exploreArticle3Title: 'Eat Healthy - Live Well',
    exploreArticle3Desc: 'Healthy eating trends and the most beloved organic and vegan restaurants.',
    exploreArticle4Title: 'Night Cuisine - Saigon Never Sleeps',
    exploreArticle4Desc: 'Explore exciting night dishes and the most vibrant late-night eateries in Saigon.',
    exploreArticle5Title: 'Traditional Dishes - Timeless Flavors',
    exploreArticle5Desc: 'Traditional dishes preserving authentic flavors through generations.',
    exploreArticle6Title: 'Fusion Food - Limitless Creativity',
    exploreArticle6Desc: 'Unique combinations of Vietnamese cuisine with world cuisines.',
    places: 'places',
    aiOdysseus: 'Odysseus AI',
    aiAssistant: 'AI Assistant',
    restaurantSuggestion: 'Restaurant Suggestion',
    menuFoodCNN: 'Image Analysis',
    aiSelectMode: 'Select mode',
    aiTypePlaceholder: 'Type a message...',
    aiSend: 'Send',
    aiUploadImage: 'Upload image',
    aiAnalyzing: 'Analyzing...',
    aiViewOnMap: 'View on map',
    aiDetails: 'Details',
    aiTranslateMenu: 'Translate menu',
    aiSuggestingRestaurants: 'Finding restaurants...',
    aiNoResult: 'No matching results found.',
    aiWelcomeRestaurant:
      "Hi! I'm Odysseus. Describe the food or restaurant type you want, and I'll suggest some for you!",
    aiWelcomeImage: 'Hi! Upload an image of a menu, food, or place and I will analyze it for you.',
    aiWelcomeAssistant:
      "Hi! I'm Odysseus, FoOdyssey's AI assistant. This feature is under development.",
    aiComingSoon: 'Feature coming soon',
    aiImageMenu: 'This is a menu. Let me translate it for you:',
    aiImageFood: 'This is a dish! Restaurants serving this:',
    aiImagePlace: 'This is a location! Matching places:',
    setYourLocation: 'Set Your Location',
    dragToSetLocation: 'Drag to set location',
    confirmLocation: 'Confirm Location',
    cancel: 'Cancel',
    latestFoodNews: 'Latest Food News',
    popularArticles: 'Popular Articles',
    views: 'views',
    comments: 'comments',
    currentLocation: 'Current Location',
    yourLocation: 'Your Location',
    loadingMap: 'Loading map...',
    searchError: 'An error occurred while searching',
    loadRestaurantError: 'Could not load restaurant details',
    filterLoading: 'Loading...',
  },
};

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

export function LanguageProvider({ children }: { children: ReactNode }) {
  const [language, setLanguage] = useState<Language>('vi');

  const t = (key: string): string => {
    return translations[language][key as keyof typeof translations.vi] || key;
  };

  return (
    <LanguageContext.Provider value={{ language, setLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  );
}

export function useLanguage() {
  const context = useContext(LanguageContext);
  if (!context) {
    throw new Error('useLanguage must be used within LanguageProvider');
  }
  return context;
}
