from fastapi import APIRouter, Depends
from sqlalchemy.orm import Session
from app.db.session import get_db
from app.modules.ai.schemas import ChatBoxRequest, ChatBoxResponse
from app.modules.ai.ai_facade import ai_facade

router = APIRouter(
    prefix="/ai",
    tags=["AI Interactions"]
)

@router.post("/chatbox", response_model=ChatBoxResponse)
def chatbox(request: ChatBoxRequest, db: Session = Depends(get_db)) -> ChatBoxResponse:
    """
    Takes user text input and prompts Groq AI (or returns mock data)
    to recommend a list of restaurants.

    Args:
        request (ChatBoxRequest): The payload containing the user's message.
        db (Session): The database session.

    Returns:
        ChatBoxResponse: Recommended restaurants generated by the AI service.
    """
    return ai_facade.handle_chatbox(request, db)
