from fastapi import APIRouter
from app.modules.ai.schemas import ChatBoxRequest, ChatBoxResponse
from app.modules.ai.ai_facade import ai_facade

router = APIRouter(
    prefix="/ai",
    tags=["AI Interactions"]
)

@router.post("/chatbox", response_model=ChatBoxResponse)
def chatbox(request: ChatBoxRequest) -> ChatBoxResponse:
    """
    Takes user text input and prompts an AI model (or returns mock data)
    to recommend a list of restaurants.

    Args:
        request (ChatBoxRequest): The payload containing the user's message.

    Returns:
        ChatBoxResponse: Recommended restaurants generated by the AI service.
    """
    return ai_facade.handle_chatbox(request)
