"""add dishes table

Revision ID: b1cde844c734
Revises: merge_heads_fix
Create Date: 2026-04-19 13:18:26.102504

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
"""add dishes table

Revision ID: b1cde844c734
Revises: merge_heads_fix
Create Date: 2026-04-19 13:18:26.102504

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b1cde844c734'
down_revision: Union[str, Sequence[str], None] = 'merge_heads_fix'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('dishes',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('slug', sa.String(length=255), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('slug')
    )
    op.create_index(op.f('ix_dishes_name'), 'dishes', ['name'], unique=True)
    op.create_table('place_dishes',
    sa.Column('place_id', sa.Integer(), nullable=False),
    sa.Column('dish_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['dish_id'], ['dishes.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['place_id'], ['places.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('place_id', 'dish_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('place_dishes')
    op.drop_index(op.f('ix_dishes_name'), table_name='dishes')
    op.drop_table('dishes')
    # ### end Alembic commands ###
