"""rename firebase_uid to supabase_id

Revision ID: da64c06227ba
Revises: ef73c6a9a68b
Create Date: 2026-04-18 20:52:10.065080

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'da64c06227ba'
down_revision: Union[str, Sequence[str], None] = 'ef73c6a9a68b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('supabase_id', sa.String(length=128), nullable=False))
    op.drop_index(op.f('ix_users_firebase_uid'), table_name='users')
    op.create_index(op.f('ix_users_supabase_id'), 'users', ['supabase_id'], unique=True)
    op.drop_column('users', 'firebase_uid')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('firebase_uid', sa.VARCHAR(length=128), autoincrement=False, nullable=False))
    op.drop_index(op.f('ix_users_supabase_id'), table_name='users')
    op.create_index(op.f('ix_users_firebase_uid'), 'users', ['firebase_uid'], unique=True)
    op.drop_column('users', 'supabase_id')
    # ### end Alembic commands ###
